version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: zita_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: zita_db
      TZ: America/Guayaquil
    ports:
      - "5433:5432"
    volumes:
      # 🌟 RUTA FÍSICA: Guarda la BD en la carpeta de tu proyecto
      - ./postgres_datos:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: zita_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Guayaquil 
      - TZ=America/Guayaquil
    volumes:
      # 🌟 RUTA FÍSICA: Guarda los flujos en la carpeta de tu proyecto
      - ./n8n_config:/home/node/.n8n
    depends_on:
      - db

